### ISSUE TITLE
setup 1.7 image

### ISSUE THREAD

**Issue by exemplari** [Mailu/infra#11]
I tried to spin up the setup `docker-compose up -d` but and the only container that did not start was stable 1.7

so i run it `docker-compose up stable` and get some python error

File "/usr/local/lib/python3.9/site-packages/flask/blueprints.py", line 195, in __init__
stable_1       |     raise ValueError("'name' may not contain a dot '.' character.")
stable_1       | ValueError: 'name' may not contain a dot '.' character.

the other containers , 'development' and 'testing' are working 

I played around with the .env file and putting `STABLE=1_7` and fixing the docker-compose.yml to pull the correct image will at least boot. I think the issue is in the python scripts. 

```
  stable:
    image: mailu/setup:1.7
```

**Comment by Diman0** [comment]
This is the wrong location to report issues. In the future use the [Mailu repo](https://github.com/Mailu/Mailu/issues) for reporting issues with the Mailu project.
This issue is already resolved. Flask introduced a breaking change that required changes in the setup image.
