### ISSUE TITLE
Let's collect public keys

### ISSUE THREAD

**Issue by kaiyou** [Mailu/infra#2]
Here we shall collect project managers public keys for accessing the docs and setup machine(s).

Please use a specific ssh keypair so that any any attack on the key you publish here can lead to anything else than Mailu being compromised.

Please use `rsa` (>= 2048), `ecds` (>=256) or `ed25519`.

**Comment by Nebukadneza** [comment]
OK, I’ll go first then:
```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIDI4SRx3rWoos1dXQymO8OdcY9pdPVXmzu6AteUM/fm nebukadneza@mailu-setup-key
```
