### ISSUE TITLE
Setup doesn't allow valid paths

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/infra#22]
I had `/abc/x.y.z/mailu` specified as path in setup, but setup refused to accept it. I had to use `/mailu` and edit it afterwards manually. Would be more convenient if it supported the original path though.

**Comment by nazar-pc** [comment]
I just noticed this is likely the wrong repository, feel free to move all 3 issues I reported so far into the correct one.

**Comment by Diman0** [comment]
This issue is created in the wrong project. This issue can be created in the Mailu project.
Mailu issues can be reported here: https://github.com/Mailu/Mailu/issues
Kubernetes related issues can be reported here: https://github.com/Mailu/helm-charts
