### ISSUE TITLE
"mail" certs option didn't add ":ro" for volume mount

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/infra#23]
Generated configuration was this:
```yaml
      - "/mailu/certs:/certs"
```
Though I think this is more appropriate since Mailu is not supposed to generate certificates in this case on its own, thus read-only access should suffice:
```yaml
      - "/mailu/certs:/certs:ro"
```

**Comment by Diman0** [comment]
This issue is created in the wrong project. This issue can be created in the Mailu project.
Mailu issues can be reported here: https://github.com/Mailu/Mailu/issues
Kubernetes related issues can be reported here: https://github.com/Mailu/helm-charts
