### ISSUE TITLE
"restart: always" is not a great default

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/infra#24]
Generally `restart: unless-stopped` is a better default since some may want to stop container temporarily for whatever reason and having it restarting automatically is inconvenient.

**Comment by Diman0** [comment]
This issue is created in the wrong project. It can be created in the Mailu project.
Mailu issues can be reported here: https://github.com/Mailu/Mailu/issues
Kubernetes issues can be reported here: https://github.com/Mailu/helm-charts

**Comment by nazar-pc** [comment]
Cant you just move it to correct repo?
